import AuthProvider from "./component/Provider";
import { Suspense } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic"; // Import dynamic from Next.js for dynamic import
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Logical Quiz",
  description: "Generated by create next app",
};

// Dynamically import FirstNav component
const FirstNav = dynamic(() => import("./components/FirstNav.js"));

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div>
            <Suspense fallback={<div>Loading...</div>}>
              <FirstNav />
            </Suspense>
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
